name: AirSim Integration Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: testing/AirSimTests/log/C_auto_path_coords.log
      - name: Require new logs
        if: steps.changed-files.outputs.any_changed == 'false'
        run: exit 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Set up Pythonpath
        run: |
          echo "PYTHONPATH=${PYTHONPATH}:${GITHUB_WORKSPACE}/src/central_control/scripts:${GITHUB_WORKSPACE}/src/cruise_control/scripts:${GITHUB_WORKSPACE}/src/lane_keep_assist/scripts:${GITHUB_WORKSPACE}/src/lidar_object_recognition/scripts:${GITHUB_WORKSPACE}/src/mapping_navigation/scripts:${GITHUB_WORKSPACE}/src/sensors/scripts:${GITHUB_WORKSPACE}/src/sign_car_recognition/scripts:${GITHUB_WORKSPACE}/src/common/src" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow sympy images-upload-cli
      - name: Run metrics on base test NH
        run: |
          python testing/AirSimTests/log_analyzer.py C_auto_path_coords --pr-branch=${{ github.event.pull_request.head.ref }},${{ github.event.pull_request.head.sha }}
      - name: Comment metrics if PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: pr_message.txt
